name: Build iOS App

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest  # You can also use 'macos-14' if preferred

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # If you don't use CocoaPods, you can remove this step:
      # - name: Install CocoaPods (if needed)
      #   run: |
      #     sudo gem install cocoapods
      #     pod install

      - name: Build the app
        run: |
          xcodebuild -project FitNotes.xcodeproj \
                     -scheme FitNotes \
                     -configuration Release \
                     clean build CODE_SIGNING_ALLOWED=NO
